language: php

php:
  # PHP 5.4 (5.4.28) is the version currently being used on our production server
  - 5.4
  # PHP 5.5 is the current latest release
  - 5.5

install:
  # Initialise the database instance for the test
  - mysqladmin -uroot create ca_test
  - mysql -uroot -e "create user 'ca_test'@'localhost' identified by 'password';"
  - mysql -uroot -e "grant all on ca_test.* to 'ca_test'@'localhost';"
  # Set environment variables
  - export COLLECTIVEACCESS_HOME="$(pwd)"
  - export PATH="$PATH:$COLLECTIVEACCESS_HOME/support/bin"
  # Create setup.php
  - ln -s .travis.setup.php setup.php
  # Install the WAM CMIS profile
  - support/bin/caUtils install --hostname=localhost --setup="$(pwd)/tests/setup-tests.php" --profile-name=wamcmis --admin-email=dev@gaiaresources.com.au >install.log

before_script:
  # Go into the tests directory to run the tests
  - cd tests/
