language: php

php:
  # PHP 5.4 (5.4.28) is the version currently being used on our production server
  - 5.4
  # PHP 5.5 is the current latest release
  - 5.5

mysql:
  # MySQL settings, these correspond to the settings used by the test-install script
  database: ca_test
  username: ca_test
  password: password
  encoding: utf8

install:
  # Get the tools, we need the test-install script, which wraps `caUtils install`
  - git clone https://github.com/wamuseum/cmis-tools.git
  # Create the database instance for the test
  - mysqladmin -uroot create ca_test
  # Create the database user and grant privileges
  - mysql -uroot -e "create user 'ca_test'@'localhost' identified by 'password';"
  - mysql -uroot -e "grant all on ca_test.* to 'ca_test'@'localhost';"
  # Set environment variables
  - export COLLECTIVEACCESS_HOME="$(pwd)"
  - export PATH="$PATH:$COLLECTIVEACCESS_HOME/support/bin"
  # Install the WAM CMIS profile
  - cmis-tools/bin/test-install
  # Create setup.php as link to setup.php-dist
  - ln -s setup.php-dist setup.php
  # Change phpunit.xml to use the setup.php used by test-install
  - sed -e "s?bootstrap=\".*\"?bootstrap=\"../cmis-tools/conf/test-install/setup.php\"?g" --in-place tests/phpunit.xml
  - cat tests/phpunit.xml
  - mysql -uca_test -ppassword -e "show tables;"

before_script:
  # Go into the tests directory to run the tests
  - cd tests/
